spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      location:
      file-size-threshold:
  profiles:
    active: local
  jmx:
    enabled: false
server:
  port: 18888
